image: "registry.sensetime.com/spring/dka:pytorch1.5.0_fix"

before_script:
  - gcc --version
  - nvcc --version
  - nvidia-smi
  - python -c "import torch; print(torch.__version__);"
  - python -c "from torch.utils.collect_env import get_pretty_env_info; print(get_pretty_env_info())"
  - python -c "from spring import nart"


style:
  tags:
    - gpu
    - diamond
  stage: build
  script:
    - pip install flake8
    - flake8 .
  except:
    - schedules


docs:
  tags:
    - gpu
    - diamond
  stage: deploy
  script:
    - export MAX_JOBS=8
    - pip install sphinx==1.5.6
    - pip install docutils==0.17.1
    - pip install http://spring.sensetime.com/pypi/packages/sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl
    - pip install http://spring.sensetime.com/pypi/packages/sphinxcontrib_versioning-2.2.1-py3-none-any.whl
    - git --version
    - export PYTHONPATH=.:$PYTHONPATH
    - sphinx-versioning build docs/source docs/_build/html
    - sshpass -p springpypi ssh -o 'StrictHostKeyChecking no' -p 10000 spring@10.10.40.93 'if [ -d ~/up ]; then mv ~/up ~/up_bak; fi'
    - sshpass -p springpypi scp -o 'StrictHostKeyChecking no' -P 10000 -r docs/_build/html spring@10.10.40.93:~/up
    - sshpass -p springpypi ssh -o 'StrictHostKeyChecking no' -p 10000 spring@10.10.40.93 'if [ -d ~/up_bak ]; then rm -r ~/up_bak; fi'
    - echo "update up docs done"
    only:
    - schedules
