runtime:
  rank_init: False
num_kpts: &num_kpts 17

evaluator: &evaluator                  # evaluation metric
  type: hkd_COCO_Evaluator
  kwargs:
    gt_file: /mnt/lustre/share/DSK/datasets/mscoco2017/annotations/person_keypoints_val2017.json
    iou_types: ['keypoints']

dataset: # Required.
  train:
    dataset:
      type: keypoint_train
      kwargs:
        source: train  # dataset id
        meta_file: /mnt/lustre/share/DSK/datasets/mscoco2017/annotations/person_keypoints_train2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: /mnt/lustre/share/DSK/datasets/mscoco2017/train2017
            color_mode: RGB
        num_kpts: *num_kpts
        radius: [2]
        strides: [4]
        keep_aspect_ratio: True
        means: [0.485,0.456,0.406]
        stds: [0.229,0.224,0.225]
        img_norm_factor: 255.0
        crop_square: false
        in_h: 256
        in_w: 192
        scale_center: 1
        scale_factor: 0.3
        rot: 40
        label_type: 'Gaussian'
        bg: True
        flip: true
        evaluator: *evaluator
  test:
    dataset:
      type: keypoint_test
      kwargs:
        source: val
        meta_file: /mnt/lustre/share/DSK/datasets/mscoco2017/annotations/person_keypoints_val2017.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: /mnt/lustre/share/DSK/datasets/mscoco2017/val2017
            color_mode: RGB
        num_kpts: *num_kpts
        keep_aspect_ratio: True
        means: [0.485,0.456,0.406]
        stds: [0.229,0.224,0.225]
        img_norm_factor: 255.0
        crop_square: false
        in_h: 256
        in_w: 192
        box_scale: 1.0
        inst_score_thres: 0
        evaluator: *evaluator

  batch_sampler:
    type: base
    kwargs:
      sampler:
        type: dist
        kwargs: {}
      batch_size: 64
  dataloader:
    type: pytorch
    kwargs:
      num_workers: 4
      pin_memory: True

trainer: # Required.
  max_epoch: 140              # total epochs for the training
  test_freq: 10
  save_freq: 10
  optimizer:                 # optimizer = SGD(params,lr=0.001,momentum=0.9,weight_decay=0.0001)
    type: Adam
    kwargs:
      lr: 0.002
#      lr: 0.00003125
  lr_scheduler:              # lr_scheduler = MultStepLR(optimizer, milestones=[9,14],gamma=0.1)
    warmup_epochs: 0         # set to be 0 to disable warmup. When warmup,  target_lr = init_lr * total_batch_size
    warmup_register_type: no_scale_lr
    type: MultiStepLR
    kwargs:
      milestones: [90, 120]     # epochs to decay lr
      gamma: 0.1             # decay rate

saver: # Required.
  save_dir: checkpoints/res18_sb_hkd     # dir to save checkpoints
  results_dir: results_dir/res18_sb_hkd  # dir to save detection results. i.e., bboxes, masks, keypoints
  auto_resume: False  # find last checkpoint from save_dir and resume from it automatically
                     # this option has the highest priority (auto_resume > opts > resume_model > pretrain_model)
  pretrain_model: /mnt/lustre/share/DSK/model_zoo/pytorch/imagenet/resnet18-5c106cde.pth

hooks:
  - type: auto_checkpoint
  - type: train_val_logger
    kwargs:
      freq: 10
      skip_first_k: 5
      logdir: log

net:
  - name: backbone              # backbone = resnet50(frozen_layers, out_layers, out_strides)
    type: resnet18
    kwargs:
      frozen_layers: []     # layer0...1 is fixed
      out_layers: [4]     # layer1...4, commonly named Conv2...5
      out_strides: [32]  # tell the strides of output features
      normalize:
        type: solo_bn
      initializer:
        method: msra
#      task: detection
  - name: kpt_sb_head
    prev: backbone
    type: keypoint_sb
    kwargs:
      inplanes: 512
      mid_channels: 256
      num_classes: *num_kpts
      has_bg: true
      test_with_gaussian_filter: false
      loss:
        type: kp_mse
